<?php
use App\Helpers\Url;
$isEditing = $note !== null && isset($note['id']);
$errors = $feedback['errors'] ?? [];
$blocks = $note['blocos'] ?? [];
require dirname(__DIR__) . '/layouts/header.php';
?>
<div class="app-shell"><?php require dirname(__DIR__) . '/layouts/sidebar.php'; ?><div class="app-content"><?php require dirname(__DIR__) . '/layouts/navbar.php'; ?><main class="page-content notes-page">
<section class="page-heading"><div><p class="eyebrow">Notas Rápidas</p><h1><?= $isEditing ? 'Editar nota' : 'Nova nota' ?></h1><p>Organize seu conteúdo em blocos e ajuste a ordem quando precisar.</p></div><a href="<?= Url::to('/notas') ?>" class="btn btn-light">Cancelar</a></section>
<?php if ($errors !== []): ?><div class="alert alert-danger border-0 shadow-sm"><?php foreach ($errors as $error): ?><div><?= htmlspecialchars((string) $error, ENT_QUOTES, 'UTF-8') ?></div><?php endforeach; ?></div><?php endif; ?>
<form method="post" action="<?= $isEditing ? Url::to('/notas/' . rawurlencode((string) $note['id']) . '/editar') : Url::to('/notas') ?>" id="note-form">
<input type="hidden" name="_csrf_token" value="<?= htmlspecialchars((string) $csrfToken, ENT_QUOTES, 'UTF-8') ?>">
<div class="row g-4"><div class="col-12 col-xl-8"><section class="card border-0 shadow-sm"><div class="card-body p-3 p-md-4"><div class="mb-3"><label class="form-label fw-semibold">Título</label><input class="form-control form-control-lg" name="titulo" required maxlength="255" value="<?= htmlspecialchars((string) ($note['titulo'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" placeholder="Ex.: Resumo da aula 03"></div><div class="mb-3"><label class="form-label fw-semibold">Conteúdo da nota</label><textarea class="form-control" name="conteudo" rows="5" placeholder="Escreva uma visão geral ou deixe o conteúdo nos blocos abaixo."><?= htmlspecialchars((string) ($note['conteudo'] ?? ''), ENT_QUOTES, 'UTF-8') ?></textarea></div></div></section>
<section class="mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 fw-bold mb-1">Blocos da nota</h2><p class="text-muted small mb-0">Arraste pela ordem usando os controles ou adicione um novo bloco.</p></div><button class="btn btn-outline-primary" type="button" id="add-block"><i class="bi bi-plus-lg me-1"></i>Adicionar bloco</button></div><div id="blocks" class="d-flex flex-column gap-3"><?php foreach ($blocks as $block): ?><div class="card border-0 shadow-sm note-block"><div class="card-body p-3"><div class="d-flex align-items-center gap-2 mb-3"><span class="text-muted"><i class="bi bi-grip-vertical"></i></span><select name="blocos_tipo[]" class="form-select form-select-sm block-type"><option value="texto" <?= ($block['tipo_bloco'] ?? '') === 'texto' ? 'selected' : '' ?>>Texto</option><option value="codigo" <?= ($block['tipo_bloco'] ?? '') === 'codigo' ? 'selected' : '' ?>>Código</option><option value="imagem" <?= ($block['tipo_bloco'] ?? '') === 'imagem' ? 'selected' : '' ?>>Imagem</option><option value="lista" <?= ($block['tipo_bloco'] ?? '') === 'lista' ? 'selected' : '' ?>>Lista</option><option value="equacao" <?= ($block['tipo_bloco'] ?? '') === 'equacao' ? 'selected' : '' ?>>Equação</option></select><button type="button" class="btn btn-sm btn-light move-up" aria-label="Mover bloco para cima"><i class="bi bi-arrow-up"></i></button><button type="button" class="btn btn-sm btn-light move-down" aria-label="Mover bloco para baixo"><i class="bi bi-arrow-down"></i></button><button type="button" class="btn btn-sm btn-outline-danger remove-block" aria-label="Remover bloco"><i class="bi bi-trash"></i></button></div><textarea class="form-control block-content" name="blocos_conteudo[]" rows="4" placeholder="Conteúdo do bloco"><?= htmlspecialchars((string) ($block['conteudo'] ?? ''), ENT_QUOTES, 'UTF-8') ?></textarea></div></div><?php endforeach; ?></div></section></div>
<aside class="col-12 col-xl-4"><section class="card border-0 shadow-sm"><div class="card-body p-4"><label class="form-label fw-semibold">Disciplina</label><select name="disciplina_id" class="form-select mb-4"><option value="">Sem disciplina</option><?php foreach ($disciplines as $discipline): ?><option value="<?= htmlspecialchars((string) $discipline['id'], ENT_QUOTES, 'UTF-8') ?>" <?= (($note['disciplina_id'] ?? '') === $discipline['id']) ? 'selected' : '' ?>><?= htmlspecialchars((string) $discipline['nome'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select><?php if ($isEditing): ?><div class="small text-muted border-top pt-3 mb-4"><div>Criada: <?= date('d/m/Y H:i', strtotime($note['criado_em'])) ?></div><div>Atualizada: <?= date('d/m/Y H:i', strtotime($note['atualizado_em'])) ?></div></div><?php endif; ?><button class="btn btn-primary w-100" type="submit"><i class="bi bi-check-lg me-1"></i><?= $isEditing ? 'Salvar alterações' : 'Criar nota' ?></button></div></section><?php if ($isEditing): ?><button class="btn btn-outline-danger w-100 mt-3" type="submit" form="delete-note-form"><i class="bi bi-trash me-1"></i>Excluir nota</button><?php endif; ?></aside></div></form>
<?php if ($isEditing): ?><form id="delete-note-form" method="post" action="<?= Url::to('/notas/' . rawurlencode((string) $note['id']) . '/excluir') ?>" onsubmit="return confirm('Excluir esta nota e todos os seus blocos?');"><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars((string) $csrfToken, ENT_QUOTES, 'UTF-8') ?>"></form><?php endif; ?>
</main></div></div><?php require dirname(__DIR__) . '/layouts/mobile-navigation.php'; ?>
<template id="block-template"><div class="card border-0 shadow-sm note-block"><div class="card-body p-3"><div class="d-flex align-items-center gap-2 mb-3"><span class="text-muted"><i class="bi bi-grip-vertical"></i></span><select name="blocos_tipo[]" class="form-select form-select-sm block-type"><option value="texto">Texto</option><option value="codigo">Código</option><option value="imagem">Imagem</option><option value="lista">Lista</option><option value="equacao">Equação</option></select><button type="button" class="btn btn-sm btn-light move-up" aria-label="Mover bloco para cima"><i class="bi bi-arrow-up"></i></button><button type="button" class="btn btn-sm btn-light move-down" aria-label="Mover bloco para baixo"><i class="bi bi-arrow-down"></i></button><button type="button" class="btn btn-sm btn-outline-danger remove-block" aria-label="Remover bloco"><i class="bi bi-trash"></i></button></div><textarea class="form-control block-content" name="blocos_conteudo[]" rows="4" placeholder="Conteúdo do bloco"></textarea></div></div></template>
<script>document.addEventListener('DOMContentLoaded',()=>{const blocks=document.getElementById('blocks'),template=document.getElementById('block-template');function bind(block){block.querySelector('.remove-block').addEventListener('click',()=>block.remove());block.querySelector('.move-up').addEventListener('click',()=>{const prev=block.previousElementSibling;if(prev) blocks.insertBefore(block,prev)});block.querySelector('.move-down').addEventListener('click',()=>{const next=block.nextElementSibling;if(next) blocks.insertBefore(next,block)});}blocks.querySelectorAll('.note-block').forEach(bind);document.getElementById('add-block').addEventListener('click',()=>{const block=template.content.firstElementChild.cloneNode(true);bind(block);blocks.append(block);block.querySelector('textarea').focus();});});</script>
<?php require dirname(__DIR__) . '/layouts/footer.php'; ?>
