<?php
use App\Helpers\Url;
$errors = $feedback['errors'] ?? [];
$formatDate = static fn (?string $date): string => $date ? date('d/m/Y H:i', strtotime($date)) : 'Ainda não aberta';
require dirname(__DIR__) . '/layouts/header.php';
?>
<div class="app-shell"><?php require dirname(__DIR__) . '/layouts/sidebar.php'; ?><div class="app-content"><?php require dirname(__DIR__) . '/layouts/navbar.php'; ?><main class="page-content library-page">
<section class="page-heading"><div><p class="eyebrow">Leitura</p><h1>Biblioteca</h1><p>Continue a leitura dos seus PDFs e EPUBs.</p></div><button class="btn btn-primary d-inline-flex align-items-center gap-2" data-bs-toggle="modal" data-bs-target="#add-book"><i class="bi bi-plus-lg"></i>Adicionar arquivo</button></section>
<?php if (isset($feedback['success'])): ?><div class="alert alert-success border-0 shadow-sm"><?= htmlspecialchars((string) $feedback['success'], ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<?php if ($errors !== []): ?><div class="alert alert-danger border-0 shadow-sm"><?php foreach ($errors as $error): ?><div><?= htmlspecialchars((string) $error, ENT_QUOTES, 'UTF-8') ?></div><?php endforeach; ?></div><?php endif; ?>
<?php if ($books === []): ?><div class="card border-0 shadow-sm"><div class="card-body text-center py-5 text-muted"><i class="bi bi-bookshelf fs-1 d-block mb-3"></i><strong class="d-block text-dark mb-1">Sua estante está vazia</strong><span>Adicione um PDF ou EPUB dos seus arquivos para começar.</span></div></div><?php else: ?><div class="row g-4"><?php foreach ($books as $book): ?>
<div class="col-12 col-sm-6 col-lg-4 col-xxl-3"><article class="card border-0 shadow-sm h-100 library-book"><div class="library-cover d-flex align-items-center justify-content-center"><i class="bi <?= strtolower((string) $book['extensao']) === 'epub' ? 'bi-book' : 'bi-file-earmark-pdf' ?>"></i></div><div class="card-body p-3"><span class="badge text-bg-light border text-uppercase mb-2"><?= htmlspecialchars((string) $book['extensao'], ENT_QUOTES, 'UTF-8') ?></span><h2 class="h6 fw-bold text-truncate" title="<?= htmlspecialchars((string) $book['nome_original'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars((string) $book['nome_original'], ENT_QUOTES, 'UTF-8') ?></h2><p class="small text-muted mb-3 text-truncate"><?= htmlspecialchars((string) ($book['disciplina_nome'] ?? 'Sem disciplina'), ENT_QUOTES, 'UTF-8') ?></p><div class="progress mb-2" style="height:7px"><div class="progress-bar" style="width:<?= max(0, min(100, (float) $book['progresso_porcentagem'])) ?>%"></div></div><div class="d-flex justify-content-between text-muted small mb-3"><span><?= number_format((float) $book['progresso_porcentagem'], 0) ?>%</span><span><?= (int) $book['total_paginas'] > 0 ? 'Pág. ' . (int) $book['pagina_atual'] . '/' . (int) $book['total_paginas'] : 'Preparando leitura' ?></span></div><div class="small text-muted mb-3"><i class="bi bi-clock-history me-1"></i><?= $formatDate($book['ultimo_acesso'] ?? null) ?></div><a class="btn btn-primary w-100" href="<?= Url::to('/arquivos/visualizar/' . rawurlencode((string) $book['arquivo_id'])) ?>">Ler agora</a></div></article></div>
<?php endforeach; ?></div><?php endif; ?>
</main></div></div><?php require dirname(__DIR__) . '/layouts/mobile-navigation.php'; ?>
<div class="modal fade" id="add-book" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content border-0 shadow" method="post" action=""><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars((string) $csrfToken, ENT_QUOTES, 'UTF-8') ?>"><div class="modal-header border-0"><h2 class="modal-title fs-5">Adicionar à estante</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><?php if ($available === []): ?><p class="text-muted mb-0">Não há PDFs ou EPUBs disponíveis nos seus arquivos.</p><?php else: ?><label class="form-label">Arquivo compatível</label><select class="form-select" id="library-file"><option value="">Selecione um arquivo</option><?php foreach ($available as $file): ?><option value="<?= htmlspecialchars((string) $file['id'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars((string) $file['nome_original'], ENT_QUOTES, 'UTF-8') ?> (<?= strtoupper((string) $file['extensao']) ?>)</option><?php endforeach; ?></select><?php endif; ?></div><div class="modal-footer border-0"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit" <?= $available === [] ? 'disabled' : '' ?>>Adicionar</button></div></form></div></div>
<script>document.querySelector('#add-book form')?.addEventListener('submit',(event)=>{const id=document.getElementById('library-file').value;if(!id){event.preventDefault();return;}event.currentTarget.action=<?= json_encode(Url::to('/biblioteca/')) ?>+encodeURIComponent(id)+'/adicionar';});</script>
<?php require dirname(__DIR__) . '/layouts/footer.php'; ?>
