<?php
use App\Helpers\Url;

$color = is_string($discipline['cor']) && preg_match('/^#[0-9a-fA-F]{6}$/', $discipline['cor']) ? $discipline['cor'] : '#2563eb';
$formatDate = static fn (?string $value): string => $value ? (new \DateTimeImmutable($value))->format('d/m/Y') : 'Sem data definida';
$minutes = $discipline['minutos_estudados'] === null ? null : (int) $discipline['minutos_estudados'];
$duration = $minutes === null ? '—' : ($minutes < 60 ? $minutes . ' min' : intdiv($minutes, 60) . 'h' . ($minutes % 60 ? ' ' . ($minutes % 60) . 'min' : ''));
$priority = ['baixa' => 'Baixa', 'media' => 'Média', 'alta' => 'Alta'];
$status = ['a_fazer' => 'A fazer', 'em_andamento' => 'Em andamento', 'concluido' => 'Concluído'];
require dirname(__DIR__) . '/layouts/header.php';
?>
<div class="app-shell"><?php require dirname(__DIR__) . '/layouts/sidebar.php'; ?><div class="app-content"><?php require dirname(__DIR__) . '/layouts/navbar.php'; ?><main class="page-content discipline-detail-page">
    <a class="back-link" href="<?= Url::to('/disciplinas') ?>"><i class="bi bi-arrow-left"></i>Todas as disciplinas</a>
    <section class="discipline-hero" style="--discipline-color: <?= htmlspecialchars($color, ENT_QUOTES, 'UTF-8') ?>"><span class="discipline-hero-icon"><i class="bi <?= htmlspecialchars(\App\Validators\DisciplineValidator::safeIcon((string) $discipline['icone']), ENT_QUOTES, 'UTF-8') ?>"></i></span><div><p class="eyebrow">Disciplina</p><h1><?= htmlspecialchars((string) $discipline['nome'], ENT_QUOTES, 'UTF-8') ?></h1><p>Criada em <?= $formatDate($discipline['criado_em']) ?></p></div><a class="btn btn-light ms-auto" href="<?= Url::to('/disciplinas/' . rawurlencode((string) $discipline['id']) . '/editar') ?>"><i class="bi bi-pencil me-2"></i>Editar</a></section>
    <section class="discipline-stat-grid"><article><span>Arquivos</span><strong><?= (int) $discipline['arquivos_count'] ?></strong></article><article><span>Tarefas</span><strong><?= (int) $discipline['tarefas_count'] ?></strong><small><?= (int) $discipline['tarefas_concluidas_count'] ?> concluídas</small></article><article><span>Notas</span><strong><?= (int) $discipline['notas_count'] ?></strong></article><article><span>Tempo estudado</span><strong><?= $duration ?></strong><small><?= $minutes === null ? 'sem sessões registradas' : 'total registrado' ?></small></article></section>
    <section class="discipline-content-grid">
        <article class="dashboard-card"><div class="card-heading"><div><h2>Arquivos</h2><p>Materiais recentes desta disciplina.</p></div><i class="bi bi-folder2-open card-heading-icon"></i></div><?php if ($files === []): ?><div class="empty-state"><i class="bi bi-folder2-open"></i><p>Não há arquivos nesta disciplina.</p></div><?php else: ?><div class="compact-list"><?php foreach ($files as $file): ?><div class="compact-row"><span class="file-icon"><i class="bi bi-file-earmark"></i></span><div class="text-truncate"><strong class="d-block text-truncate"><?= htmlspecialchars((string) ($file['nome_original'] ?: $file['nome_arquivo']), ENT_QUOTES, 'UTF-8') ?></strong><small><?= $formatDate($file['criado_em']) ?></small></div></div><?php endforeach; ?></div><?php endif; ?></article>
        <article class="dashboard-card"><div class="card-heading"><div><h2>Tarefas</h2><p>Tarefas associadas à disciplina.</p></div><i class="bi bi-check2-square card-heading-icon"></i></div><?php if ($tasks === []): ?><div class="empty-state"><i class="bi bi-check2-square"></i><p>Não há tarefas nesta disciplina.</p></div><?php else: ?><div class="compact-list"><?php foreach ($tasks as $task): ?><div class="compact-row"><span class="task-check"><i class="bi bi-circle"></i></span><div class="text-truncate"><strong class="d-block text-truncate"><?= htmlspecialchars((string) $task['titulo'], ENT_QUOTES, 'UTF-8') ?></strong><small><?= $priority[$task['prioridade']] ?? htmlspecialchars((string) $task['prioridade'], ENT_QUOTES, 'UTF-8') ?> · <?= $status[$task['status']] ?? htmlspecialchars((string) $task['status'], ENT_QUOTES, 'UTF-8') ?><?= $task['data_vencimento'] ? ' · ' . $formatDate($task['data_vencimento']) : '' ?></small></div></div><?php endforeach; ?></div><?php endif; ?></article>
        <article class="dashboard-card"><div class="card-heading"><div><h2>Notas</h2><p>Notas atualizadas recentemente.</p></div><i class="bi bi-journal-text card-heading-icon"></i></div><?php if ($notes === []): ?><div class="empty-state"><i class="bi bi-journal-text"></i><p>Não há notas nesta disciplina.</p></div><?php else: ?><div class="compact-list"><?php foreach ($notes as $note): ?><div class="compact-row"><span class="note-icon"><i class="bi bi-sticky"></i></span><div class="text-truncate"><strong class="d-block text-truncate"><?= htmlspecialchars((string) $note['titulo'], ENT_QUOTES, 'UTF-8') ?></strong><small>Atualizada em <?= $formatDate($note['atualizado_em']) ?></small></div></div><?php endforeach; ?></div><?php endif; ?></article>
        <article class="dashboard-card danger-card"><div class="card-heading"><div><h2>Excluir disciplina</h2><p>Esta ação não pode ser desfeita.</p></div><i class="bi bi-exclamation-triangle card-heading-icon"></i></div><p class="danger-copy">Ao excluir, <?= (int) $discipline['arquivos_count'] ?> arquivo(s), <?= (int) $discipline['tarefas_count'] ?> tarefa(s) e <?= (int) $discipline['notas_count'] ?> nota(s) permanecerão no seu perfil, mas sem disciplina associada, conforme as regras do banco.</p><button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#delete-discipline">Excluir disciplina</button></article>
    </section>
</main></div></div><?php require dirname(__DIR__) . '/layouts/mobile-navigation.php'; ?>
<div class="modal fade" id="delete-discipline" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content border-0 rounded-4" method="post" action="<?= Url::to('/disciplinas/' . rawurlencode((string) $discipline['id']) . '/excluir') ?>"><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><div class="modal-header border-0"><h2 class="modal-title fs-5">Excluir “<?= htmlspecialchars((string) $discipline['nome'], ENT_QUOTES, 'UTF-8') ?>”?</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>Os registros associados não serão apagados, mas perderão a associação com esta disciplina:</p><ul class="mb-0"><li><?= (int) $discipline['arquivos_count'] ?> arquivo(s)</li><li><?= (int) $discipline['tarefas_count'] ?> tarefa(s)</li><li><?= (int) $discipline['notas_count'] ?> nota(s)</li></ul></div><div class="modal-footer border-0"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-danger">Excluir definitivamente</button></div></form></div></div>
<?php require dirname(__DIR__) . '/layouts/footer.php'; ?>
